In [62]:
import numpy as np
import tensorflow as tf
import tensorflow.keras


In [159]:
x = tf.constant([0.3, 0.8])
tf.math.sigmoid(x), tf.math.softmax(x)



(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.5744425, 0.6899744], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.37754068, 0.62245935], dtype=float32)>)

In [146]:
y_true = [[0, 1], [0, 1]]
y_pred = [[0.05, 0.95], [0.1, 0.8]]
# Using 'auto'/'sum_over_batch_size' reduction type.
cce = tf.keras.losses.CategoricalCrossentropy()
cce(y_true, y_pred).numpy()


0.08453816

In [97]:
s1 = -1*(np.log(0.95) + np.log(0.8)) #+ np.log(0.8)))
s2 = -1*(np.log(1-0.05) + np.log(1- 0.1)) #+ np.log(0.8)))
r = (s1 + s2)/2
s1,s2, (s1 + s2), (s1 + s2)/2, (s1 + s2)/4

(0.2744368457017603,
 0.2744368457017603,
 0.5488736914035206,
 0.2744368457017603,
 0.13721842285088015)

In [139]:
y_true = [[0, 1], [0, 1]]
y_pred = [[0.05, 0.95], [0.1, 0.8]]
# Using 'auto'/'sum_over_batch_size' reduction type.
cce = tf.keras.losses.BinaryCrossentropy()
cce(y_true, y_pred).numpy(), (np.log(0.95) + np.log(0.8)) /2


(0.10777254, -0.13721842285088015)

In [143]:
y_true = [0, 1]
y_pred = [[0.95, 0.05], [0.1, 0.8]]
# Using 'auto'/'sum_over_batch_size' reduction type.
cce = tf.keras.losses.SparseCategoricalCrossentropy()
cce(y_true, y_pred).numpy(), (np.log(1-0.95) + np.log(0.8)) /2

(0.08453818, -1.6094379124340998)

In [155]:
y_true = [[0, 1], [0, 1]]
y_pred = [[0.05, 0.95], [0.1, 0.8]]

s = tf.nn.softmax(y_pred)

x1 = np.log(1 - 0.2890505) + np.log(0.7109495)
x2 = np.log(1 - 0.3318122) + np.log(0.66818774)
e = tf.nn.softmax_cross_entropy_with_logits(y_true, y_pred)
b = tf.keras.losses.BinaryCrossentropy()
cce = tf.keras.losses.CategoricalCrossentropy()
s,x1/2, x2/2, e, tf.reduce_mean(e), b(y_true, s), cce(y_true, s)

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.2890505 , 0.7109495 ],
        [0.3318122 , 0.66818774]], dtype=float32)>,
 -0.34115387842433875,
 -0.40318605213030445,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.34115392, 0.40318608], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.37217>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.3721698>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.37216997>)